#!/usr/bin/env bash
set -euo pipefail

CHECKOUT_ROOT_INPUT="${1:-$(pwd)}"
CHECKOUT_ROOT="$(python3 - "$CHECKOUT_ROOT_INPUT" <<'PY'
import os
import sys
print(os.path.realpath(sys.argv[1]))
PY
)"

REPO_ROOT="$(git -C "$CHECKOUT_ROOT" rev-parse --show-toplevel)"
RUNTIME_DIR="$CHECKOUT_ROOT/.checkout-runtime"
RUNTIME_FILE="$RUNTIME_DIR/runtime.env"
DATABASE_URL_SOURCE=""

mkdir -p "$RUNTIME_DIR"

read_env_value() {
  local key="$1"
  shift

  python3 - "$key" "$@" <<'PY'
import os
import sys

key = sys.argv[1]
files = sys.argv[2:]

for path in files:
    if not path or not os.path.exists(path):
        continue

    with open(path, "r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            left, right = line.split("=", 1)
            if left.strip() != key:
                continue
            value = right.strip().strip('"').strip("'")
            if value:
                print(value)
                sys.exit(0)

sys.exit(1)
PY
}

port_pair_is_free() {
  python3 - "$1" "$2" <<'PY'
import socket
import sys

ports = [int(sys.argv[1]), int(sys.argv[2])]

for port in ports:
    sock = socket.socket()
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        sock.bind(("127.0.0.1", port))
    except OSError:
        sys.exit(1)
    finally:
        sock.close()

sys.exit(0)
PY
}

find_free_pair() {
  local frontend_port=3000
  local backend_port=4000

  while true; do
    if port_pair_is_free "$frontend_port" "$backend_port"; then
      printf '%s %s\n' "$frontend_port" "$backend_port"
      return 0
    fi

    frontend_port=$((frontend_port + 1))
    backend_port=$((backend_port + 1))
  done
}

resolve_database_url() {
  if [[ -n "${DATABASE_URL:-}" ]]; then
    printf '%s\n' "$DATABASE_URL"
    return 0
  fi

  local env_sources=(
    "$CHECKOUT_ROOT/backend/.env"
    "$REPO_ROOT/backend/.env"
    "$CHECKOUT_ROOT/.env"
    "$REPO_ROOT/.env"
    "$CHECKOUT_ROOT/backend/.env.checkout"
    "$CHECKOUT_ROOT/.checkout-runtime/runtime.env"
  )

  local source_file
  for source_file in "${env_sources[@]}"; do
    if value="$(read_env_value DATABASE_URL "$source_file" 2>/dev/null)"; then
      DATABASE_URL_SOURCE="$source_file"
      printf '%s\n' "$value"
      return 0
    fi
  done

  return 1
}

upsert_env_var() {
  local file_path="$1"
  local key="$2"
  local value="$3"

  python3 - "$file_path" "$key" "$value" <<'PY'
import os
import sys

path, key, value = sys.argv[1], sys.argv[2], sys.argv[3]
line = f"{key}={value}"

content = []
if os.path.exists(path):
    with open(path, "r", encoding="utf-8") as fh:
        content = fh.read().splitlines()

updated = False
for idx, current in enumerate(content):
    if current.startswith(f"{key}="):
        content[idx] = line
        updated = True
        break

if not updated:
    content.append(line)

with open(path, "w", encoding="utf-8") as fh:
    fh.write("\n".join(content).rstrip("\n") + "\n")
PY
}

bootstrap_backend_for_e2e() {
  local backend_dir="$CHECKOUT_ROOT/backend"

  if [[ ! -d "$backend_dir" ]]; then
    return 0
  fi

  if [[ "${SKIP_RUNTIME_BOOTSTRAP:-0}" == "1" ]]; then
    printf '⚠️  Bootstrap de runtime omitido (SKIP_RUNTIME_BOOTSTRAP=1).\n'
    return 0
  fi

  printf 'Preparando backend para E2E (prisma generate + seed)...\n'
  (
    cd "$backend_dir"
    DATABASE_URL="$DATABASE_URL" pnpm prisma:generate
    DATABASE_URL="$DATABASE_URL" pnpm prisma:seed
  )
}

DATABASE_URL="$(resolve_database_url || true)"

if [[ -z "$DATABASE_URL" ]]; then
  printf 'No se pudo resolver DATABASE_URL para este checkout. Exportalo o definilo en un .env compartido.\n' >&2
  exit 1
fi

read -r FRONTEND_PORT BACKEND_PORT < <(find_free_pair)

cat > "$RUNTIME_FILE" <<EOF
# Generated by scripts/setup-checkout-runtime.sh
CHECKOUT_ROOT=$CHECKOUT_ROOT
DATABASE_URL=$DATABASE_URL
FRONTEND_PORT=$FRONTEND_PORT
BACKEND_PORT=$BACKEND_PORT
NEXT_PUBLIC_PORT=$FRONTEND_PORT
FRONTEND_BASE_URL=http://127.0.0.1:$FRONTEND_PORT
BACKEND_BASE_URL=http://127.0.0.1:$BACKEND_PORT
E2E_PORT=$FRONTEND_PORT
E2E_BASE_URL=http://127.0.0.1:$FRONTEND_PORT
NEXT_PUBLIC_API_URL=http://127.0.0.1:$BACKEND_PORT/v1
BACKEND_URL=http://127.0.0.1:$BACKEND_PORT
NEXTAUTH_URL=http://127.0.0.1:$FRONTEND_PORT
NEXTAUTH_SECRET=e2e-nextauth-secret
CHECKOUT_RUNTIME_MODE=prod
SALT_ROUND=10
JWT_SECRET=e2e-dev-secret
JWT_EXPIRATION_TIME=15m
JWT_REFRESH_EXPIRATION_TIME=7d
OPENAI_API_KEY=e2e-dev-openai-key
OPENAI_MODEL=gpt-4o-mini
TWILIO_ACCOUNT_SID=AC00000000000000000000000000000000
TWILIO_AUTH_TOKEN=00000000000000000000000000000000
TWILIO_WHATSAPP_FROM=whatsapp:+14155238886
EOF

if [[ -d "$CHECKOUT_ROOT/backend" ]]; then
  BACKEND_ENV_CHECKOUT="$CHECKOUT_ROOT/backend/.env.checkout"

  if [[ -n "$DATABASE_URL_SOURCE" && -f "$DATABASE_URL_SOURCE" ]]; then
    cp "$DATABASE_URL_SOURCE" "$BACKEND_ENV_CHECKOUT"
  else
    : > "$BACKEND_ENV_CHECKOUT"
  fi

  upsert_env_var "$BACKEND_ENV_CHECKOUT" "DATABASE_URL" "$DATABASE_URL"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "PORT" "$BACKEND_PORT"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "BACKEND_PORT" "$BACKEND_PORT"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "FRONTEND_PORT" "$FRONTEND_PORT"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "SALT_ROUND" "10"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "JWT_SECRET" "e2e-dev-secret"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "JWT_EXPIRATION_TIME" "15m"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "JWT_REFRESH_EXPIRATION_TIME" "7d"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "OPENAI_API_KEY" "e2e-dev-openai-key"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "OPENAI_MODEL" "gpt-4o-mini"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "TWILIO_ACCOUNT_SID" "AC00000000000000000000000000000000"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "TWILIO_AUTH_TOKEN" "00000000000000000000000000000000"
  upsert_env_var "$BACKEND_ENV_CHECKOUT" "TWILIO_WHATSAPP_FROM" "whatsapp:+14155238886"
fi

if [[ -d "$CHECKOUT_ROOT/frontend" ]]; then
  cat > "$CHECKOUT_ROOT/frontend/.env.checkout" <<EOF
NEXT_PUBLIC_PORT=$FRONTEND_PORT
PORT=$FRONTEND_PORT
BACKEND_PORT=$BACKEND_PORT
NEXT_PUBLIC_API_URL=http://127.0.0.1:$BACKEND_PORT/v1
NEXTAUTH_URL=http://127.0.0.1:$FRONTEND_PORT
NEXTAUTH_SECRET=e2e-nextauth-secret
EOF
fi

bootstrap_backend_for_e2e

printf 'Runtime preparado para %s\n' "$CHECKOUT_ROOT"
printf 'Frontend: http://127.0.0.1:%s\n' "$FRONTEND_PORT"
printf 'Backend:  http://127.0.0.1:%s\n' "$BACKEND_PORT"
printf 'Base de datos compartida configurada desde DATABASE_URL\n'
printf 'Sourcing sugerido: source "%s"\n' "$RUNTIME_FILE"
