#!/usr/bin/env bash
set -euo pipefail

WORKTREE_PATH_INPUT="${1:-$(pwd)}"
WORKTREE_PATH="$(python3 - "$WORKTREE_PATH_INPUT" <<'PY'
import os
import sys
print(os.path.realpath(sys.argv[1]))
PY
)"

REPO_ROOT="$(git -C "$WORKTREE_PATH" rev-parse --show-toplevel)"
RUNTIME_DIR="$WORKTREE_PATH/.worktree-runtime"
RUNTIME_FILE="$RUNTIME_DIR/runtime.env"

mkdir -p "$RUNTIME_DIR"

read_env_value() {
  local key="$1"
  shift

  python3 - "$key" "$@" <<'PY'
import os
import sys

key = sys.argv[1]
files = sys.argv[2:]

for path in files:
    if not path or not os.path.exists(path):
        continue

    with open(path, "r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            left, right = line.split("=", 1)
            if left.strip() != key:
                continue
            value = right.strip().strip('"').strip("'")
            if value:
                print(value)
                sys.exit(0)

sys.exit(1)
PY
}

port_pair_is_free() {
  python3 - "$1" "$2" <<'PY'
import socket
import sys

ports = [int(sys.argv[1]), int(sys.argv[2])]

for port in ports:
    sock = socket.socket()
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        sock.bind(("127.0.0.1", port))
    except OSError:
        sys.exit(1)
    finally:
        sock.close()

sys.exit(0)
PY
}

find_free_pair() {
  local frontend_port=3000
  local backend_port=4000

  while true; do
    if port_pair_is_free "$frontend_port" "$backend_port"; then
      printf '%s %s\n' "$frontend_port" "$backend_port"
      return 0
    fi

    frontend_port=$((frontend_port + 1))
    backend_port=$((backend_port + 1))
  done
}

DATABASE_URL="$(read_env_value DATABASE_URL \
  "$WORKTREE_PATH/backend/.env" \
  "$REPO_ROOT/backend/.env" \
  "$WORKTREE_PATH/.env" \
  "$REPO_ROOT/.env")"

read -r FRONTEND_PORT BACKEND_PORT < <(find_free_pair)

cat > "$RUNTIME_FILE" <<EOF
# Generated by scripts/setup-worktree-runtime.sh
WORKTREE_PATH=$WORKTREE_PATH
DATABASE_URL=$DATABASE_URL
FRONTEND_PORT=$FRONTEND_PORT
BACKEND_PORT=$BACKEND_PORT
PORT=$BACKEND_PORT
NEXT_PUBLIC_PORT=$FRONTEND_PORT
NEXT_PUBLIC_API_URL=http://127.0.0.1:$BACKEND_PORT/v1
BACKEND_URL=http://127.0.0.1:$BACKEND_PORT
EOF

if [[ -d "$WORKTREE_PATH/backend" ]]; then
  cat > "$WORKTREE_PATH/backend/.env.worktree" <<EOF
DATABASE_URL=$DATABASE_URL
PORT=$BACKEND_PORT
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
EOF
fi

if [[ -d "$WORKTREE_PATH/frontend" ]]; then
  cat > "$WORKTREE_PATH/frontend/.env.worktree" <<EOF
NEXT_PUBLIC_PORT=$FRONTEND_PORT
PORT=$FRONTEND_PORT
BACKEND_PORT=$BACKEND_PORT
NEXT_PUBLIC_API_URL=http://127.0.0.1:$BACKEND_PORT/v1
EOF
fi

printf 'Runtime preparado para %s\n' "$WORKTREE_PATH"
printf 'Frontend: http://127.0.0.1:%s\n' "$FRONTEND_PORT"
printf 'Backend:  http://127.0.0.1:%s\n' "$BACKEND_PORT"
printf 'Base de datos compartida configurada desde DATABASE_URL\n'
printf 'Sourcing sugerido: source "%s"\n' "$RUNTIME_FILE"
